name: pas_xi_kereta
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: 4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
assets:
  - assets/img/
